// src/routes/unread/unread-block.tsx
import { component$ } from "@builder.io/qwik";
import type { UnreadItemProps } from "./unread-item";
import { UnreadItem } from "./unread-item";

type UnreadBlockProps = {
  list: any[];
  title: string;
};
export const UnreadBlock = component$<UnreadBlockProps>((props) => {
  if (!props.list.length) return null;
  return (
    <article id={props.title.toLowerCase()} class="flow">
      <h2 id={props.title.toLowerCase()}>{props.title}</h2>
      <ul class="flow">
        {props.list.map((item: UnreadItemProps) => (
          <UnreadItem key={item.slug} {...item} />
        ))}
      </ul>
    </article>
  );
});

// src/routes/unread/UnreadBlock.svelte
<script lang="ts">
	import UnreadItem from './UnreadItem.svelte';

	type Book = {
		slug: string;
		title: string;
		author: string;
		translator?: string;
	};

	type Props = {
		list: Book[];
		title: string;
	};

	let { list, title }: Props = $props();
</script>

{#if list.length > 0}
	<article id={title.toLowerCase()} class="flow">
		<h2 id={title.toLowerCase()}>{title}</h2>
		<ul class="flow">
			{#each list as item (item.slug)}
				<UnreadItem {...item} />
			{/each}
		</ul>
	</article>
{/if}
