// src/routes/unplayed/UnplayedBlock.svelte
<script lang="ts">
	import UnplayedItem from './UnplayedItem.svelte';

	type Game = {
		slug: string;
		title: string;
		platform: string;
	};

	type Props = {
		list: Game[];
		title: string;
	};

	let { list, title }: Props = $props();
</script>

{#if list.length > 0}
	<article id={title.toLowerCase()} class="flow">
		<h2 id={title.toLowerCase()}>{title}</h2>
		<ul class="flow">
			{#each list as item (item.slug)}
				<UnplayedItem {...item} />
			{/each}
		</ul>
	</article>
{/if}

// src.qwik.bak/routes/unplayed/unplayed-block.tsx
import { component$ } from "@builder.io/qwik";
import { UnplayedItem } from "./unplayed-item";

type UnplayedBlockProps = {
  list: any[];
  title: string;
};
export const UnplayedBlock = component$<UnplayedBlockProps>((props) => {
  if (!props.list.length) return null;

  return (
    <article id={props.title.toLowerCase()} class="flow">
      <h2 id={props.title.toLowerCase()}>{props.title}</h2>
      <ul class="flow">
        {props.list.map((item) => (
          <UnplayedItem key={item.slug} {...item} />
        ))}
      </ul>
    </article>
  );
});
