// src/islands/CopyEmail.tsx
import { createSignal } from "solid-js";

export let CopyEmail = () => {
  let [isAnimated, setIsAnimated] = createSignal(false);

  let onClick = () => {
    navigator.clipboard.writeText("hey@brandonpittman.com").then(() => {
      setIsAnimated(true);
    });
  };

  return (
    <button
      onClick={onClick}
      onAnimationEnd={() => setIsAnimated(false)}
      class={`cta animate-once${isAnimated() ? " animation-blink" : ""}`}
    >
      Copy
    </button>
  );
};

// src/components/copy-email.tsx
import { useSignal, component$, $ } from "@builder.io/qwik";

export const CopyEmail = component$(() => {
  const isAnimated = useSignal(false);

  const onClick = $(() => {
    navigator.clipboard.writeText("hey@brandonpittman.com").then(() => {
      isAnimated.value = true;
    });
  });

  return (
    <button
      onClick$={onClick}
      onAnimationEnd$={$(() => (isAnimated.value = false))}
      class={`cta animate-once${isAnimated.value ? " animation-blink" : ""}`}
    >
      Copy
    </button>
  );
});
