// src/lib/components/SearchForm.svelte
<script lang="ts">
	import { page } from '$app/state';

	type Props = {
		placeholder?: string;
		children: any;
	};

	let { placeholder, children }: Props = $props();

	const q = $derived(page.url.searchParams.get('q') || '');
</script>

<form>
	<label for="search" class="visually-hidden">
		{@render children()}
	</label>
	<div
		class="sidebar"
		data-dir="rtl"
		style="--gutter: var(--space-2xs); --sidebar-min-inline-size: 80%; max-inline-size: var(--size-15)"
	>
		<input
			autofocus
			value={q}
			id="search"
			type="search"
			name="q"
			{placeholder}
		/>
		<button type="submit" class="cta"> Search </button>
	</div>
</form>

// src/components/search-form.tsx
import { component$, Slot } from "@builder.io/qwik";
import { useLocation } from "@builder.io/qwik-city";

export const SearchForm = component$<{ placeholder?: string }>(
  ({ placeholder }) => {
    const location = useLocation();
    const q = location.url.searchParams.get("q");

    return (
      <form
        onInput$={async ({ target }, ev) => {
          if ((target as HTMLInputElement).value.trim() === "") {
            ev.submit();
          }
        }}
      >
        <label for="search" class="visually-hidden">
          <Slot />
        </label>
        <div
          class="sidebar"
          data-dir="rtl"
          style="--gutter: var(--space-2xs); --sidebar-min-inline-size: 80%; max-inline-size: var(--size-15)"
        >
          <input
            list="datalist"
            autoFocus
            value={q}
            id="search"
            type="search"
            name="q"
            placeholder={placeholder}
          />
          <button type="submit" class="cta">
            {" "}
            Search
          </button>
        </div>
      </form>
    );
  }
);
