// src/routes/unplayed/UnplayedItem.svelte
<script lang="ts">
	type Props = {
		slug: string;
		title: string;
		platform: string;
	};

	let { slug, title, platform }: Props = $props();
</script>

<li class="flow-3xs">
	<div class="cluster gutter-3xs" style="--align: baseline;">
		<a href={`/games/${slug}`}>
			<span>{title}</span>
		</a>
		<a
			href={`/unplayed?q=${platform}`}
			class="no-underline color-gray-light text-2xs white-space-nowrap font-medium"
		>
			{platform}
		</a>
	</div>
</li>

// src/components/UnplayedItem.tsx
import { component$ } from "@builder.io/qwik";

export type UnplayedItemProps = {
  slug: string;
  title: string;
  platform: string;
};

export const UnplayedItem = component$<UnplayedItemProps>((props) => {
  return (
    <>
      <li class="flow-3xs">
        <div class="cluster gutter-3xs" style="--align: baseline;">
          <span>{props.title}</span>
          <a hidden href={`/games/${props.slug}`}>
            <span>{props.title}</span>
          </a>
          <a
            href={`/unplayed?q=${props.platform}`}
            class="no-underline color-gray-light text-2xs white-space-nowrap font-medium"
          >
            {props.platform}
          </a>
        </div>
      </li>
    </>
  );
});
