// src/islands/CopyEmail.tsx
import { createSignal } from "solid-js";

export let CopyEmail = () => {
  let [isAnimated, setIsAnimated] = createSignal(false);

  let onClick = () => {
    navigator.clipboard.writeText("hey@brandonpittman.com").then(() => {
      setIsAnimated(true);
    });
  };

  return (
    <button
      onClick={onClick}
      onAnimationEnd={() => setIsAnimated(false)}
      style={
        isAnimated()
          ? {
              animation: "var(--animation-blink)",
              "animation-iteration-count": "var(--iteration-count)",
            }
          : {}
      }
      class="cta"
    >
      Copy
    </button>
  );
};

// src/islands/CopyEmail.svelte
<script lang="ts">
export let isAnimated = false

export let onClick = () => {
  navigator.clipboard.writeText("hey@brandonpittman.com").then(() => {
    isAnimated = true
  })}
</script>

<button
  on:click={onClick}
  on:animationend={() => {
    isAnimated = false
  }}
  style={isAnimated
    ? "animation: var(--animation-blink); animation-iteration-count: 1"
    : undefined
  }
  class="cta"
>
  Copy
</button>
